version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: db
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT_HTTPS: "false"
      JAVA_OPTS_APPEND: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      DB_ADDR: legacy-db
      DB_DATABASE: legacy
      DB_USER: postgres
      DB_PASSWORD: password
    command: ["start-dev",  "--spi-storage-legacy-api-url=http://wiremock:9999"]
    volumes:
      - ./target/deploy:/opt/keycloak/providers/
      - ./src/main/resources/theme:/opt/keycloak/themes/
      - ./conf:/opt/keycloak/conf/
    ports:
    - "8080:8080"
    - "5005:5005"
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
  legacy-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: legacy
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "1234:5432"
  wiremock:
    image: wiremock/wiremock
    volumes:
      - ./wiremock-data:/home/wiremock
    command: ["--verbose", "--port", "9999"]
    ports:
      - "9999:9999"